sudo: false
language: node_js
node_js:
    - 6
    - 8
script: npm run lint && npm test
notifications:
    email:
        recipients:
            - langpavel@phpskelet.org
        on_success: change
        on_failure: always
